// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://mrejjctfuxxvfvalypdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yZWpqY3RmdXh4dmZ2YWx5cGR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTU1NTYsImV4cCI6MjA3MDA3MTU1Nn0.v5qGMRMOJj742NUxi8kvDzOi98QH97k-XMUguTI7d-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);
